// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RemoteAdmin.Infrastructure.Data;

#nullable disable

namespace RemoteAdmin.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.AgentIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentVersion")
                        .HasColumnType("text");

                    b.Property<string>("CertificateThumbprint")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastFailedJob")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastInventory")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessfulJob")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId")
                        .IsUnique();

                    b.ToTable("AgentIdentities");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.DeploymentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CommandLine")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorOutput")
                        .HasColumnType("text");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("integer");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<string>("PackageName")
                        .HasColumnType("text");

                    b.Property<string>("PackageVersion")
                        .HasColumnType("text");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("EndpointId");

                    b.ToTable("DeploymentJobs");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.Endpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Fqdn")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("Hostname")
                        .IsUnique();

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.EndpointGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EndpointGroups");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.EndpointNetworkInterface", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdapterName")
                        .HasColumnType("text");

                    b.Property<string>("ConnectionState")
                        .HasColumnType("text");

                    b.Property<string>("DnsServers")
                        .HasColumnType("text");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<string>("Gateway")
                        .HasColumnType("text");

                    b.Property<string>("Ipv4Address")
                        .HasColumnType("text");

                    b.Property<string>("Ipv6Address")
                        .HasColumnType("text");

                    b.Property<int?>("LinkSpeedMbps")
                        .HasColumnType("integer");

                    b.Property<string>("MacAddress")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.ToTable("EndpointNetworkInterfaces");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.HardwareInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Architecture")
                        .HasColumnType("text");

                    b.Property<long?>("AvailableRamMb")
                        .HasColumnType("bigint");

                    b.Property<string>("BiosVersion")
                        .HasColumnType("text");

                    b.Property<int?>("ClockSpeedMhz")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CollectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Cores")
                        .HasColumnType("integer");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<string>("GpuDriverVersion")
                        .HasColumnType("text");

                    b.Property<string>("GpuName")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InstallDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastBoot")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LogicalProcessors")
                        .HasColumnType("integer");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("ProcessorName")
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<long?>("TotalRamMb")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId")
                        .IsUnique();

                    b.ToTable("HardwareInventories");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.SoftwareInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Architecture")
                        .HasColumnType("integer");

                    b.Property<Guid>("EndpointId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("InstallDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstallPath")
                        .HasColumnType("text");

                    b.Property<string>("Publisher")
                        .HasColumnType("text");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EndpointId");

                    b.ToTable("SoftwareInventoryItems");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.StorageDrive", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("CapacityGb")
                        .HasColumnType("double precision");

                    b.Property<string>("DiskType")
                        .HasColumnType("text");

                    b.Property<string>("DriveLetter")
                        .HasColumnType("text");

                    b.Property<string>("FileSystem")
                        .HasColumnType("text");

                    b.Property<double?>("FreeSpaceGb")
                        .HasColumnType("double precision");

                    b.Property<Guid>("HardwareInventoryId")
                        .HasColumnType("uuid");

                    b.Property<double?>("UsedSpaceGb")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("HardwareInventoryId");

                    b.ToTable("StorageDrives");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.AgentIdentity", b =>
                {
                    b.HasOne("RemoteAdmin.Domain.Entities.Endpoint", "Endpoint")
                        .WithOne("AgentIdentity")
                        .HasForeignKey("RemoteAdmin.Domain.Entities.AgentIdentity", "EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.DeploymentJob", b =>
                {
                    b.HasOne("RemoteAdmin.Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RemoteAdmin.Domain.Entities.Endpoint", "Endpoint")
                        .WithMany()
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.Endpoint", b =>
                {
                    b.HasOne("RemoteAdmin.Domain.Entities.EndpointGroup", "Group")
                        .WithMany("Endpoints")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.EndpointNetworkInterface", b =>
                {
                    b.HasOne("RemoteAdmin.Domain.Entities.Endpoint", "Endpoint")
                        .WithMany("NetworkInterfaces")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.HardwareInventory", b =>
                {
                    b.HasOne("RemoteAdmin.Domain.Entities.Endpoint", "Endpoint")
                        .WithOne("HardwareInventory")
                        .HasForeignKey("RemoteAdmin.Domain.Entities.HardwareInventory", "EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.SoftwareInventoryItem", b =>
                {
                    b.HasOne("RemoteAdmin.Domain.Entities.Endpoint", "Endpoint")
                        .WithMany("SoftwareInventory")
                        .HasForeignKey("EndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endpoint");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.StorageDrive", b =>
                {
                    b.HasOne("RemoteAdmin.Domain.Entities.HardwareInventory", "HardwareInventory")
                        .WithMany("Drives")
                        .HasForeignKey("HardwareInventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HardwareInventory");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.Endpoint", b =>
                {
                    b.Navigation("AgentIdentity");

                    b.Navigation("HardwareInventory");

                    b.Navigation("NetworkInterfaces");

                    b.Navigation("SoftwareInventory");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.EndpointGroup", b =>
                {
                    b.Navigation("Endpoints");
                });

            modelBuilder.Entity("RemoteAdmin.Domain.Entities.HardwareInventory", b =>
                {
                    b.Navigation("Drives");
                });
#pragma warning restore 612, 618
        }
    }
}
